[package]
name = "fluent"
version = "0.1.0"
authors = ["Takeru Sato <type.in.type@gmail.com>"]

[dependencies]
rmp = "0.8"
rmp-serde = "0.13"
serde = "1.0"
serde_derive = "1.0"
rand = "0.4"
uuid = { version = "0.6", features = ["v4"] }
base64 = "0.9.0"
tmc = { path = "../tmc" }
